src/core/urls.py
from django.contrib import admin
from django.urls import include, path


admin.site.site_header = 'Администрирование django для демо it34meetup 01.20'

urlpatterns = [
    path('demo/', include('src.demo.urls')),
    path('admin/', admin.site.urls),
]

src/demo/urls.py
from django.urls import path

from . import views

app_name = 'demo'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

src/demo/models.py
from django.db import models
from django.utils import timezone
import datetime


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

src/demo/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "Вы не сделали выбор.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('demo:results', args=(question.id,)))

src/demo/templates/polls/detail.html
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}



<div class="container d-flex h-100">
  <div class="row align-items-center h-100 mx-auto">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">{{ question.question_text }}</h5>

        {% if error_message %}<p><strong style="color: red;">{{ error_message }}</strong></p>{% endif %}

        <form action="{% url 'demo:vote' question.id %}" method="post" class="form-group pb-0 mb-0">
          {% csrf_token %}
          {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
          {% endfor %}
          <div class="row">
            <div class="col text-center">
              <input type="submit" value="Голосовать" class="btn btn-primary" style="display: inline-block;">
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

src/demo/templates/polls/index.html
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}

<div class="container d-flex h-100">
  <div class="row align-items-center h-100 mx-auto">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Пройти опрос</h5>
{#        <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>#}
        {% if latest_question_list %}
          <ul>
            {% for question in latest_question_list %}
              <li><a href="{% url 'demo:detail' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
          </ul>
        {% else %}
          <p>No polls are available.</p>
        {% endif %}
{#        <a href="#" class="card-link">Card link</a>#}
{#        <a href="#" class="card-link">Another link</a>#}
      </div>
    </div>
  </div>
</div>

src/demo/templates/polls/results.html
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}


<div class="container d-flex h-100">
  <div class="row align-items-center h-100 mx-auto">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">{{ question.question_text }}</h5>
        <ul>
          {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} голосов</li>
          {% endfor %}
        </ul>
        <div class="row">
          <div class="col text-center">
            <a href="{% url 'demo:detail' question.id %}" class="card-link">Голосовать снова</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>